program0: program0.cpp graph.cpp graph.hpp 
	g++ -O3 -D_GLIBCXX_DEBUG -Wall -o program0.x program0.cpp graph.cpp
	
program1: program1.cpp graph.cpp graph.hpp graph_utilities.hpp
	g++ -O3 -D_GLIBCXX_DEBUG -Wall -o program1.x program1.cpp graph.cpp graph_utilities.cpp

program2: program2.cpp graph.cpp graph.hpp graph_utilities.hpp
	g++ -O3 -D_GLIBCXX_DEBUG -Wall -o program2.x program2.cpp graph.cpp graph_utilities.cpp

program3: program3.cpp graph.cpp graph.hpp graph_utilities.hpp
	g++ -O3 -D_GLIBCXX_DEBUG -Wall -o program3.x program3.cpp graph.cpp graph_utilities.cpp

program4: program4.cpp graph.cpp graph.hpp graph_utilities.hpp
	g++ -O3 -D_GLIBCXX_DEBUG -Wall -o program4.x program4.cpp graph.cpp graph_utilities.cpp

program5: program5.cpp graph.cpp graph.hpp graph_utilities.hpp
	g++ -O3 -D_GLIBCXX_DEBUG -Wall -o program5.x program5.cpp graph.cpp graph_utilities.cpp

clean: 
	rm -f program0.x program1.x program2.x program3.x program4.x program5.x

